### ISSUE TITLE
Can't connect after a while

### ISSUE THREAD

**Issue by ElieDeloumeau** [fpaezf/CS2-rcon-tool#1]
I'm unable to connect after a while with `autokick is disabled for <random player>` in the server console and I can reconnect at each changelevel

**Comment by fpaezf** [comment]
> utokick is disabled for <random player>

Mmhh.. not sure of where is the problem, i have also autokick enabled in my server and i do not have this issue. Please, try to disable autokick (mp_autokick 0) and test again. Let me know if anything changes. Thanks for your feedback.

**Comment by fpaezf** [comment]
> I'm unable to connect after a while with `autokick is disabled for <random player>` in the server console and I can reconnect at each changelevel

Mmhh.. not sure of where is the problem, i have also autokick enabled in my server and i do not have this issue. Please, try to disable autokick (mp_autokick 0) and test again. Let me know if anything changes. Thanks for your feedback.

**Comment by ElieDeloumeau** [comment]
I tried without autokick but it remains the same. I don't have further inputs to provide you sorry 😞

**Comment by fpaezf** [comment]
Hi, i left the application all night connected and no problem at all. Seems a network related issue. Can you provide aditional info?.

Are you running a local or remote server?
Is your firewall enabled?
Maybe you can privately share your rcon password to do some testing

**Comment by ElieDeloumeau** [comment]
It's a remote server, my firewall is enable but there is no network issue while the server is responding with the error mentioned in this issue body.
I sent you an email with my steam invite link to give you my rcon next time I see this problem

**Comment by exababy** [comment]
https://www.virustotal.com/gui/file/224b43898310c60e76162e7789c9a7c183a7736141a2ef072fed31cb55a9155d

**Comment by fpaezf** [comment]
> https://www.virustotal.com/gui/file/224b43898310c60e76162e7789c9a7c183a7736141a2ef072fed31cb55a9155d

A false positive. .NET applications that uses TCPClient may trigger some antivirus software.
