### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by felixgeen** [fpaezf/CS2-rcon-tool#2]
Do you know why Virus total finds 2 security vendors who flagged this file as malicious?
https://www.virustotal.com/gui/file/d1cbd54941c45ea36a252356f62eeb82d03338d065359f21968d9a41d2df79b4/detection

Malwarebytes:
MachineLearning/Anomalous.94%

SecureAge:
Malicious

**Comment by fpaezf** [comment]
Hi, it's a false positive. All .net applications that use encryption or sockets are flagged by default.
