### ISSUE TITLE
Good tool but.

### ISSUE THREAD

**Issue by asdfxD** [fpaezf/CS2-rcon-tool#3]
thanks for the usefull tool, but possible to fix special chars it showing ????? on player name.

**Comment by fpaezf** [comment]
Yes, it's a known bug, i'm looking for a workarround. Thanks for the feedback.

**Comment by fpaezf** [comment]
Fixed since v0.9rc: https://github.com/fpaezf/CS2-rcon-tool/releases/download/v0.9rc/CS2RCONv0.9rc.zip
