### ISSUE TITLE
Could not connect to the server.

### ISSUE THREAD

**Issue by brutalcinikola** [fpaezf/CS2-rcon-tool#5]
any fix for this? I have -usercon and rcon_password set up
Could not connect to the server. Check host/IP and port!

No connection could be made because the target machine actively refused it

**Comment by fpaezf** [comment]
Are you using Docker?

**Comment by asdfxD** [comment]
When you use docker, edit your IP in startup to +ip 0.0.0.0, i had the same issue with rcon and uptime monitor checking ping on port.

**Comment by fpaezf** [comment]
> When you use docker, edit your IP in startup to +ip 0.0.0.0, i had the same issue with rcon and uptime monitor checking ping on port.

Thanks for posting a solution.

Best regards.

**Comment by brutalcinikola** [comment]
> When you use docker, edit your IP in startup to +ip 0.0.0.0, i had the same issue with rcon and uptime monitor checking ping on port.

yes i use docker, and this fixed it, thank you very much kind sir

**Comment by OmarRichart** [comment]
Hi, i'm trying to connect to the server but when the +ip option prompts the following error in server.cfg:

Unknown command '+ip'!

**Comment by fpaezf** [comment]
> Hi, i'm trying to connect to the server but when the +ip option prompts the following error in server.cfg:
> 
> Unknown command '+ip'!

Er... what?

The +ip cvar has to be set in the launch command line, nothing to do with my tool!.

Explain better please!

**Comment by OmarRichart** [comment]
I am trying the solution that @ asdfxD proposes, I am running a cs2 server in docker using the cm2network/cs2 image, is the command +ip 0.0.0.0 supposed to be put in the server.cfg?

**Comment by asdfxD** [comment]
Not server.cfg

In startup commandline.

./cs2 -dedicated -console -usercon +ip 0.0.0.0 -port 27015 .......

**Comment by OmarRichart** [comment]
Works fine, thanks!
