### ISSUE TITLE
Can whe use some of the xml files to change map dropwdown

### ISSUE THREAD

**Issue by Izocel** [fpaezf/CS2-rcon-tool#6]
Or I would need to compile my own ?

**Comment by fpaezf** [comment]
Hi, map list is retrieved from the server map group. If no map group is set, the default map rotation is loaded. I will put a map list editor in the next release if that fits your needs.

**Comment by fpaezf** [comment]
Hi, now you can override the map list loading and use a custom map list. Create a new txt file with one map per line, example:

de_dust2
cs_office
awp_lego_2

Select the custom map rotation file from settings window.

Download: https://github.com/fpaezf/CS2-rcon-tool/releases/download/v0.10rc/CS2RCONv0.10rc.zip

**Comment by Izocel** [comment]
Very nice thansk a lot works like a charm could you do same for commands ?
just have a 2nd selector from list.txt

**Comment by Izocel** [comment]
@fpaezf maybe add the selector to server actions so no change for command line tab and quickier access

**Comment by fpaezf** [comment]
Sure, maybe it's better to move the maplist selector to "server actions" tab. Thanks for the feedback!
