### ISSUE TITLE
SCK_ERR: Disconnected from server...

### ISSUE THREAD

**Issue by brutalcinikola** [fpaezf/CS2-rcon-tool#8]
Ok so this morning I connected to server normally, now when i try to connect it just says disconnected at left bottom corrner and i get this message in logs: SCK_ERR: Disconnected from server...
any idea what could be causing this problem

**Comment by fpaezf** [comment]
I can't help you since i never used Docker, maybe other users can help you.
Working ok for all non Docker users.

**Comment by asdfxD** [comment]
Don't use +ip REALIP and replace REALIP with 0.0.0.0 or remove +ip completly otherwise rcon tools won't work.

**Comment by brutalcinikola** [comment]
> Don't use +ip REALIP and replace REALIP with 0.0.0.0 or remove +ip completly otherwise rcon tools won't work.

"+game_type 0 +game_mode 1 +ip 0.0.0.0 -usercon"
This is my startup line, linux
